/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tela;

import java.util.ArrayList;
import java.util.HashSet;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ricar
 */
public class cadastroCarro extends javax.swing.JFrame {

    // private ArrayList<String> listaCarros = new ArrayList();
    /**
     * Creates new form cadastroCarro
     */
    public cadastroCarro() {
        initComponents();
        // comboBoxModelo.setModel(new DefaultComboBoxModel(listaCarros.toArray()));
        tblTabelaCarro.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent event) {
                linhaSelecionada = tblTabelaCarro.getSelectedRow();
            }
        });
    }
    private int linhaSelecionada = -1;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        comboBoxMarca = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        textNovoModelo = new javax.swing.JTextField();
        btSalvar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTabelaCarro = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        textAnoCarro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btAtualizar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btSalvarAtu = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Carro");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Marca:");

        comboBoxMarca.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        comboBoxMarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01 - Chevrolet", "02 - Fiat", "03 - Volkswagen", "04 - Hyundai", "05 - Toyota", "06 - Jeep", "07 - Renault", "08 - Honda", "09 - Nissan", "10 - Peugeot" }));
        comboBoxMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxMarcaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Modelo:");

        textNovoModelo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textNovoModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNovoModeloActionPerformed(evt);
            }
        });

        btSalvar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        tblTabelaCarro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblTabelaCarro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Marca", "Modelo", "Ano"
            }
        ));
        jScrollPane2.setViewportView(tblTabelaCarro);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Ano:");

        textAnoCarro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textAnoCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textAnoCarroActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Cadastre um Carro");

        btAtualizar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btAtualizar.setText("Atualizar");
        btAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarActionPerformed(evt);
            }
        });

        btExcluir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btSalvarAtu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btSalvarAtu.setText("Salvar Atualização");
        btSalvarAtu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarAtuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textNovoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboBoxMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textAnoCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btSalvar)
                                    .addComponent(btSalvarAtu))
                                .addGap(55, 55, 55)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btAtualizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btExcluir)))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btExcluir)
                            .addComponent(btAtualizar))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(comboBoxMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textNovoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textAnoCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btSalvarAtu)
                        .addGap(94, 94, 94))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void textNovoModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNovoModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNovoModeloActionPerformed


    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        // TODO add your handling code here:
        String modeloCarro = textNovoModelo.getText();
        String anoCarro = textAnoCarro.getText();

        String modeloText = textNovoModelo.getText();
        String marcaSelecionada = comboBoxMarca.getSelectedItem().toString();

        DefaultTableModel tabelaCarro = (DefaultTableModel) tblTabelaCarro.getModel();

        Object[] tblCarro = new Object[]{
            marcaSelecionada,
            modeloText,
            anoCarro
        };
        tabelaCarro.addRow(tblCarro);
        textNovoModelo.setText("");
        textAnoCarro.setText("");
    }//GEN-LAST:event_btSalvarActionPerformed


    private void comboBoxMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxMarcaActionPerformed

    private void textAnoCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textAnoCarroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textAnoCarroActionPerformed

    private void btAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarActionPerformed
        // TODO add your handling code here:
        
        int linhaSelecionada = tblTabelaCarro.getSelectedRow();
        
        if (linhaSelecionada == -1) {
            JOptionPane.showConfirmDialog(this, "Selecione uma linha para atualizar !");
        } else{
            DefaultTableModel tabelaCarro = (DefaultTableModel) tblTabelaCarro.getModel();
            String marca = tabelaCarro.getValueAt(linhaSelecionada, 0).toString();
            String modeloCarro = tabelaCarro.getValueAt(linhaSelecionada, 1).toString();
            String anoCarro = tabelaCarro.getValueAt(linhaSelecionada, 2).toString();

            textNovoModelo.setText(modeloCarro);
            textAnoCarro.setText(anoCarro);
            comboBoxMarca.setSelectedItem(marca);
            comboBoxMarca.setEnabled(false);
        }


    }//GEN-LAST:event_btAtualizarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        // TODO add your handling code here:

        int linhaSelectDelete = tblTabelaCarro.getSelectedRow();

        if (linhaSelectDelete == -1) {
            JOptionPane.showConfirmDialog(rootPane, "Selecione uma linha para excluir !");
        } else {
            DefaultTableModel tabelaCarro = (DefaultTableModel) tblTabelaCarro.getModel();

            tabelaCarro.removeRow(linhaSelectDelete);
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btSalvarAtuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarAtuActionPerformed
        // TODO add your handling code here:
        int linhaSelecionada = tblTabelaCarro.getSelectedRow();
        
        if (linhaSelecionada == -1) {
            JOptionPane.showConfirmDialog(this, "Selecione uma linha para atualizar !");
        } else {
        DefaultTableModel tabelaCarro = (DefaultTableModel) tblTabelaCarro.getModel();
        tabelaCarro.setValueAt(comboBoxMarca.getSelectedItem(), linhaSelecionada, 0);
        tabelaCarro.setValueAt(textNovoModelo.getText(), linhaSelecionada, 1);
        tabelaCarro.setValueAt(textAnoCarro.getText(), linhaSelecionada, 2);

        textAnoCarro.setText("");
        textNovoModelo.setText("");
        comboBoxMarca.setEnabled(true);
            
        }
        
    }//GEN-LAST:event_btSalvarAtuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastroCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastroCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastroCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastroCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastroCarro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAtualizar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btSalvar;
    private javax.swing.JButton btSalvarAtu;
    private javax.swing.JComboBox<String> comboBoxMarca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblTabelaCarro;
    private javax.swing.JTextField textAnoCarro;
    private javax.swing.JTextField textNovoModelo;
    // End of variables declaration//GEN-END:variables
}
